-- CREATE TABLE

DROP TABLE EZEN.TB_DEPT_TEMP PURGE;
CREATE TABLE EZEN.TB_DEPT_TEMP(
		DEPT_CD CHAR(6) NOT NULL,
		DEPT_NM VARCHAR2(150) NOT NULL,
		UPPER_DEPT_CD CHAR(6)
);

ALTER TABLE EZEN.TB_DEPT_TEMP ADD CONSTRAINT PK_TB_DEPT_TEMP PRIMARY KEY(DEPT_CD) ;

DROP TABLE EZEN.TB_EMP_TEMP PURGE;
CREATE TABLE EZEN.TB_EMP_TEMP(
		EMP_NO char(10) NOT NULL,
		EMP_NM varchar2(150) NOT NULL,
		BIRTH_DE char(8) NOT NULL,
		LUNAR_YN char(1) NOT NULL,
		SEX_CD char(3) NOT NULL,
		ADDR varchar2(1000) NOT NULL,
		TEL_NO varchar2(150) NOT NULL,
		FINAL_EDU_SE_CD char(3) NOT NULL,
		SAL_TRANS_BANK_CD char(3) NOT NULL,
		SAL_TRANS_ACCNT_NO varchar2(20) NOT NULL,
		DIRECT_MANAGER_EMP_NO char(10),
		DEPT_CD char(6) NOT null
);

ALTER TABLE EZEN.TB_EMP_TEMP  ADD CONSTRAINT PK_TB_EMP_TEMP PRIMARY KEY(EMP_NO);
ALTER TABLE EZEN.TB_EMP_TEMP  ADD CONSTRAINT FK_TB_EMP_TEMP_01 FOREIGN KEY(DEPT_CD) REFERENCES EZEN.TB_DEPT_TEMP(DEPT_CD);

-- 컬럼 추가 
-- 테이블의 마지막 컬럼이 되며, 컬럼의 위치를 지정할 수는 없다.
ALTER TABLE EZEN.TB_EMP_TEMP ADD (MARRIED_YN CHAR(1));

-- 컬럼 삭제
-- 한번 삭제된 컬럼은 복구 불가능
ALTER TABLE EZEN.TB_EMP_TEMP DROP (MARRIED_YN);

-- 컬럼 수정
-- 컬럼의 크기를 늘리수는 있지만 줄이지는 못함
-- NULL값만 가지고 있거나 아무 행도 없으면 줄일수 있음.
-- NOVALIDATE : DEFALULT 값을 바꾸면 변경 작업 이후 발생하는 행 삽입에만 영향을 미침.
ALTER TABLE EZEN.TB_EMP_TEMP MODIFY(MARRIED_YN CHAR(1) DEFAULT 'N' NOT NULL) ;


























