-- 사원들 중 가장 생일이 늦은 사원과 빠른사원의 생년월일 그리고 총 사원수를 표시하시오.

SELECT MAX(BIRTH_DE), MIN(BIRTH_DE), COUNT(*)  
FROM EZEN.TB_EMP ;

-- 사원 중 부서코드 별 가장 늦은 생일, 가장 빠른 생일, 직원 수를 출혁하시오

SELECT A.DEPT_CD ,(SELECT B.DEPT_NM FROM TB_DEPT B WHERE B.DEPT_CD = A.DEPT_CD) AS DEPT_NM ,MAX(A.BIRTH_DE) AS "가장 늦은 생년월일", MIN(A.BIRTH_DE) AS "가장 빠른 생년월일", COUNT(*) AS 직원수
FROM TB_EMP A
GROUP BY A.DEPT_CD 
ORDER BY A.DEPT_CD ;

-- 사원 중 부서코드 별 가장 늦은 생일, 가장 빠른 생일, 직원 수를 출혁하시오
-- 각 부서별 직원수가 3명을 초과하는 부서
-- (DEPT_CD, DEPT_NM, 가장 늦은 생년월일,가장 빠른 생년월일)

SELECT A.DEPT_CD ,(SELECT B.DEPT_NM FROM TB_DEPT B WHERE B.DEPT_CD = A.DEPT_CD) AS DEPT_NM ,MAX(A.BIRTH_DE) AS "가장 늦은 생년월일", MIN(A.BIRTH_DE) AS "가장 빠른 생년월일", COUNT(*) AS 직원수
FROM TB_EMP A
GROUP BY A.DEPT_CD 
HAVING (COUNT(*)>3)
ORDER BY A.DEPT_CD ;

-- 2019년도의 급여 내역 중에서 직원 별로 평균 급여액이 470만원 이상인 직원들의
-- 직원번호, 직원명, 최대급여액수, 최소급여액수 , 평균 급여 액수를 출력하시오.

SELECT A.EMP_NO AS "직원번호",
	   (SELECT B.EMP_NM  FROM TB_EMP B WHERE A.EMP_NO=B.EMP_NO) AS "직원명",
	   MAX(A.PAY_AMT) AS "최대급여액수",
	   MIN(A.PAY_AMT) AS "최소급여액수",
	    AVG(A.PAY_AMT) AS "평균급여액수" 
FROM TB_SAL_HIS A
WHERE A.PAY_DE BETWEEN '20190101' AND '20191231'
GROUP BY A.EMP_NO  
HAVING  round(AVG(A.PAY_AMT),2) >= 4700000
ORDER BY A.EMP_NO ;

-- 2019년도의 급여 내역 중 급여의 합계(연봉)가 5500만원을 초과하는 직원의 
-- 직원번호, 직원명, 합계금여액을 출력하시오.

SELECT A.EMP_NO AS "직원번호",
		(SELECT E.EMP_NM  FROM TB_EMP E WHERE A.EMP_NO = E.EMP_NO) AS "직원명",
		SUM(A.PAY_AMT) AS "합계급여액"
FROM TB_SAL_HIS A
WHERE A.PAY_DE  BETWEEN '20190101' AND '20191231'
HAVING SUM(A.PAY_AMT) > 55000000
GROUP BY A.EMP_NO 
ORDER BY SUM(A.PAY_AMT)  DESC;

-- CASE WHEN
SELECT 
		SUM(CASE WHEN A.BIRTH_DE LIKE '195%' THEN 1 ELSE 0 END) AS "1950년대생",
		SUM(CASE WHEN A.BIRTH_DE LIKE '196%' THEN 1 ELSE 0 END) AS "1960년대생",
		SUM(CASE WHEN A.BIRTH_DE LIKE '197%' THEN 1 ELSE 0 END) AS "1970년대생",
		SUM(CASE WHEN A.BIRTH_DE LIKE '198%' THEN 1 ELSE 0 END) AS "1980년대생",
		SUM(CASE WHEN A.BIRTH_DE LIKE '199%' THEN 1 ELSE 0 END) AS "1990년대생",
		COUNT(*) AS CNT
FROM TB_EMP A
;

-- 부서별 직원들이 몇 십년대 생인지에 대한 카운트를 표시하시오.
-- 부서번호, 부서명, 1950년대생,,,,, CNT

SELECT A.DEPT_CD AS "부서번호", (SELECT B.DEPT_NM  FROM TB_DEPT B WHERE A.DEPT_CD=B.DEPT_CD) AS 부서명,
		SUM(CASE WHEN A.BIRTH_DE LIKE '195%' THEN 1 ELSE 0 END) AS "1950년대생",
		SUM(CASE WHEN A.BIRTH_DE LIKE '196%' THEN 1 ELSE 0 END) AS "1960년대생",
		SUM(CASE WHEN A.BIRTH_DE LIKE '197%' THEN 1 ELSE 0 END) AS "1970년대생",
		SUM(CASE WHEN A.BIRTH_DE LIKE '198%' THEN 1 ELSE 0 END) AS "1980년대생",
		SUM(CASE WHEN A.BIRTH_DE LIKE '199%' THEN 1 ELSE 0 END) AS "1990년대생",
		COUNT(*) AS CNT
FROM TB_EMP A 
GROUP BY A.DEPT_CD 
ORDER BY A.DEPT_CD ;

-- 자격증명을 기준으로 정렬하시오.

SELECT a.CERTI_CD ,a.CERTI_NM ,a.ISSUE_INSTI_NM 
FROM TB_CERTI a
ORDER BY a.CERTI_NM DESC 
;

SELECT a.CERTI_CD ,a.CERTI_NM AS name ,a.ISSUE_INSTI_NM 
FROM TB_CERTI a
ORDER BY name 
;

-- select 절에 존재하지 않는 컬럼으로 정렬 가능
SELECT a.CERTI_CD , a.ISSUE_INSTI_NM 
FROM tb_certi a
ORDER BY a.CERTI_NM DESC ;





























