--

SELECT LEVEL LVL, LPAD(' ',4*(LEVEL-1)) || EMP_NO || '(' || EMP_NM || ')' AS "조직인원",
		A.DEPT_CD ,B.DEPT_NM, CONNECT_BY_ISLEAF 
FROM TB_EMP A, TB_DEPT B
WHERE A.DEPT_CD = B.DEPT_CD 
START WITH A.DIRECT_MANAGER_EMP_NO IS NULL -- 관리자 사원번호가 널인 값을 시작 값으로 함
CONNECT BY PRIOR A.EMP_NO = A.DIRECT_MANAGER_EMP_NO ;

-- L패드
SELECT 30,LPAD(30,5),LPAD(30,5,'0'),LPAD(30,5,'A')
FROM DUAL;

-- 서브 쿼리
-- EMP_NO가 "1000000005"가 속한 팀의 팀원을 조회하는 SQL문을 작성하시오.


SELECT A.EMP_NO , A.EMP_NM , A.DEPT_CD 
FROM TB_EMP A
WHERE A.DEPT_CD = (SELECT A.DEPT_CD  FROM TB_EMP A WHERE A.EMP_NO = '1000000005'); 

-- TB_EMP, TB_SAL_HIS
-- 2020년 5월 기준 평균 이상의 급여를 받고 있는 직원들의 리스트를 출력하시오.

SELECT B.EMP_NO ,B.EMP_NM , A.PAY_DE ,A.PAY_AMT 
FROM TB_SAL_HIS A JOIN TB_EMP B ON A.EMP_NO =B.EMP_NO 
WHERE A.PAY_DE ='20200525' AND A.PAY_AMT 
>= (SELECT AVG(D.PAY_AMT) FROM TB_SAL_HIS D WHERE D.PAY_DE = '20200525'); 

--  서브쿼리
SELECT AVG(A.PAY_AMT)
FROM TB_SAL_HIS A 
WHERE A.PAY_DE LIKE '20200525';

-- 한국데이터베이스진흥원에서 발급한 자격증 가지고 있는 
-- 사원 번호 및 보유 자격증 개수를 출력하시오.

SELECT A.EMP_NO , COUNT(*)
FROM TB_EMP_CERTI A
WHERE A.CERTI_CD IN 
(SELECT C.CERTI_CD 
FROM TB_CERTI C 
WHERE C.ISSUE_INSTI_NM = '한국데이터베이스진흥원')
GROUP BY A.EMP_NO 
ORDER BY A.EMP_NO DESC;

-- 서브쿼리
SELECT C.CERTI_CD 
FROM TB_CERTI C 
WHERE C.ISSUE_INSTI_NM = '한국데이터베이스진흥원';


-- 다중 쿼리
-- 한 부서에 2명 이상 있는 부서중에서 각 부서의 생일기준 나이가 제일 많은 사원을 출력하시오.
-- emp_no, emp_name, dept_cd, dept_nm, birth_de

SELECT A.EMP_NO , A.EMP_NM , B.DEPT_CD ,B.DEPT_NM ,A.BIRTH_DE 
FROM TB_EMP A , TB_DEPT B 
WHERE (A.DEPT_CD,A.BIRTH_DE) IN 
(
SELECT K.DEPT_CD , MIN(K.BIRTH_DE) AS MIN_BIRTH_DE
FROM EZEN.TB_EMP K
GROUP BY K.DEPT_CD 
HAVING COUNT(*) > 1
)
AND A.DEPT_CD =B.DEPT_CD 
ORDER BY A.EMP_NO 
;
-- 서브쿼리
SELECT K.DEPT_CD , MIN(K.BIRTH_DE) AS MIN_BIRTH_DE
FROM EZEN.TB_EMP K
GROUP BY K.DEPT_CD 
HAVING COUNT(*) > 1;

-- 직원들 중 주소가 강남인 직원이 소속된 부서코드와 부서명을 출력하시오.
-- EXISTS문 서브쿼리

SELECT A.DEPT_CD , A.DEPT_NM 
FROM TB_DEPT A 
WHERE EXISTS 
(
SELECT  1
FROM TB_EMP K
WHERE K.DEPT_CD = A.DEPT_CD 
AND K.ADDR LIKE '%강남%'
)
;

-- 한국데이터베이스진흥원에서 발급한 자격증을 가지고 있는 사람의
-- 사원번호, 사원명, 자격증 코드, 자격증명을 출력하시오.
-- 스칼라 서브쿼리 
SELECT A.EMP_NO , ( SELECT M.EMP_NM  FROM TB_EMP M WHERE M.EMP_NO=A.EMP_NO) AS EMP_NM 
						, A.CERTI_CD , ( SELECT L.CERTI_NM  FROM TB_CERTI L WHERE A.CERTI_CD =L.CERTI_CD) 
FROM TB_EMP_CERTI A
WHERE A.CERTI_CD  IN 
(
SELECT K.CERTI_CD 
FROM TB_CERTI K
WHERE K.ISSUE_INSTI_NM = '한국데이터베이스진흥원'
)
ORDER BY EMP_NO  ;
;
SELECT K.CERTI_CD 
FROM TB_CERTI K
WHERE K.ISSUE_INSTI_NM = '한국데이터베이스진흥원'
;

-- 한국데이터베이스진흥원에서 발급한 자격증을 가지고 있는 사원의
-- 사원번호, 사원명, 자격증 코드, 자격증명을 출력하시오.
-- 인라인 뷰 사용


FROM(
	SELECT K.CERTI_CD 
	FROM TB_CERTI K
	WHERE K.ISSUE_INSTI_NM = '한국데이터베이스 진흥원'
) A
,TB_EMP_CERTI B
WHERE A.CERTI

CREATE VIEW V_TB_SAL_HIS_MAX_BY_EMP_NO AS 
SELECT A.EMP_NO , A.EMP_NM , B.DEPT_CD ,B.DEPT_NM ,MAX(C.PAY_AMT) AS MAX_PAY_AMT 
FROM TB_EMP A, TB_DEPT B, TB_SAL_HIS C
WHERE A.EMP_NO = C.EMP_NO  AND A.DEPT_CD = B.DEPT_CD 
GROUP BY A.EMP_NO , A.EMP_NM , B.DEPT_CD , B.DEPT_NM 
;
SELECT *
FROM V_TB_SAL_HIS_MAX_BY_EMP_NO 
;

DROP VIEW V_TB_SAL_HIS_MAX_BY_EMP_NO ;

SELECT * FROM T_MEMBER ORDER BY JOINDATE DESC;























