--

SELECT LEVEL LVL, LPAD(' ',4*(LEVEL-1)) || EMP_NO || '(' || EMP_NM || ')' AS "조직인원",
		A.DEPT_CD ,B.DEPT_NM, CONNECT_BY_ISLEAF 
FROM TB_EMP A, TB_DEPT B
WHERE A.DEPT_CD = B.DEPT_CD 
START WITH A.DIRECT_MANAGER_EMP_NO IS NULL -- 관리자 사원번호가 널인 값을 시작 값으로 함
CONNECT BY PRIOR A.EMP_NO = A.DIRECT_MANAGER_EMP_NO ;

-- L패드
SELECT 30,LPAD(30,5),LPAD(30,5,'0'),LPAD(30,5,'A')
FROM DUAL;

-- 서브 쿼리
-- EMP_NO가 "1000000005"가 속한 팀의 팀원을 조회하는 SQL문을 작성하시오.


SELECT A.EMP_NO , A.EMP_NM , A.DEPT_CD 
FROM TB_EMP A
WHERE A.DEPT_CD = (SELECT A.DEPT_CD  FROM TB_EMP A WHERE A.EMP_NO = '1000000005'); 

-- TB_EMP, TB_SAL_HIS
-- 2020년 5월 기준 평균 이상의 급여를 받고 있는 직원들의 리스트를 출력하시오.

SELECT B.EMP_NO ,B.EMP_NM , A.PAY_DE ,A.PAY_AMT 
FROM TB_SAL_HIS A JOIN TB_EMP B ON A.EMP_NO =B.EMP_NO 
WHERE A.PAY_DE ='20200525' AND A.PAY_AMT 
>= (SELECT AVG(D.PAY_AMT) FROM TB_SAL_HIS D WHERE D.PAY_DE = '20200525'); 

--  서브쿼리
SELECT AVG(A.PAY_AMT)
FROM TB_SAL_HIS A 
WHERE A.PAY_DE LIKE '20200525';

-- 한국데이터베이스진흥원에서 발급한 자격증 가지고 있는 
-- 사원 번호 및 보유 자격증 개수를 출력하시오.

SELECT A.EMP_NO , COUNT(*)
FROM TB_EMP_CERTI A
WHERE A.CERTI_CD IN 
(SELECT C.CERTI_CD 
FROM TB_CERTI C 
WHERE C.ISSUE_INSTI_NM = '한국데이터베이스진흥원')
GROUP BY A.EMP_NO 
ORDER BY A.EMP_NO DESC;

-- 서브쿼리
SELECT C.CERTI_CD 
FROM TB_CERTI C 
WHERE C.ISSUE_INSTI_NM = '한국데이터베이스진흥원';
















