DROP TABLE discounts;
CREATE TABLE discounts (
		discount_id 	number  GENERATED BY DEFAULT AS IDENTITY, 
		discount_name 	varchar2(255) NOT NULL,
		amount 			NUMBER (3, 1) NOT NULL,
		start_date 		DATE 		NOT NULL,
		expired_date	DATE 		NOT NULL 
);
COMMIT;

INSERT INTO DISCOUNTS (
						DISCOUNT_NAME,
						AMOUNT ,
						START_DATE ,
						EXPIRED_DATE 
					)
			VALUES	(
						'Spring Promotion',
						9.5 ,
						DATE '2022-05-01',
						DATE '2022-05-31'
			);
INSERT INTO DISCOUNTS (
						DISCOUNT_NAME,
						AMOUNT ,
						START_DATE ,
						EXPIRED_DATE 
					)
			VALUES	(
						'Summer Promotion',
						10.5 ,
						current_date,
						DATE '2022-05-31'
			);
		
COMMIT;
SELECT *
FROM DISCOUNTS d ;

CREATE TABLE PARTS(
	part_id		NUMBER		GENERATED BY DEFAULT AS IDENTITY ,
	part_name	varchar2(50)NOT NULL,
	lead_time	NUMBER(2,0)	NOT NULL,
	cost		NUMBER(9,2) NOT NULL,
	status		number(1,0)	NOT NULL,
	PRIMARY key(part_id)
);
COMMIT;

INSERT INTO PARTS(PART_NAME, LEAD_TIME, COST, STATUS)VALUES('sed dictum',5,134,0);

--추가 생성
INSERT INTO PARTS(PART_NAME, LEAD_TIME, COST, STATUS)VALUES('aed dictum',5,62,1);
INSERT INTO PARTS(PART_NAME, LEAD_TIME, COST, STATUS)VALUES('eed dictum',5,82,1);
INSERT INTO PARTS(PART_NAME, LEAD_TIME, COST, STATUS)VALUES('ied dictum',5,10,1);
INSERT INTO PARTS(PART_NAME, LEAD_TIME, COST, STATUS)VALUES('srd dictum',5,116,0);
INSERT INTO PARTS(PART_NAME, LEAD_TIME, COST, STATUS)VALUES('sad dictum',5,169,0);
INSERT INTO PARTS(PART_NAME, LEAD_TIME, COST, STATUS)VALUES('sdd dictum',5,116,0);
INSERT INTO PARTS(PART_NAME, LEAD_TIME, COST, STATUS)VALUES('shd dictum',5,197,1);
INSERT INTO PARTS(PART_NAME, LEAD_TIME, COST, STATUS)VALUES('set dictum',5,146,0);
INSERT INTO PARTS(PART_NAME, LEAD_TIME, COST, STATUS)VALUES('ted dictum',5,153,1);
INSERT INTO PARTS(PART_NAME, LEAD_TIME, COST, STATUS)VALUES('aed dictum',5,146,0);
INSERT INTO PARTS(PART_NAME, LEAD_TIME, COST, STATUS)VALUES('sey dictum',5,123,0);
INSERT INTO PARTS(PART_NAME, LEAD_TIME, COST, STATUS)VALUES('scd dictum',5,904,0);
INSERT INTO PARTS(PART_NAME, LEAD_TIME, COST, STATUS)VALUES('sqd dictum',5,874,0);
INSERT INTO PARTS(PART_NAME, LEAD_TIME, COST, STATUS)VALUES('oed dictum',5,334,0);
INSERT INTO PARTS(PART_NAME, LEAD_TIME, COST, STATUS)VALUES('med dictum',5,224,1);
commit;

select *
from parts
order by part_id;

update parts set cost = 130 where part_id = 1;

update parts set lead_time = 30, cost = 120, status =1 where part_id = 5;
commit;

update parts set cost = cost * 1.05;
rollback;






















