-- 서브 쿼리
-- EMP_NO가 "1000000005"가 속한 팀의 팀원을 조회하는 SQL문을 작성하시오.


SELECT A.EMP_NO , A.EMP_NM , A.DEPT_CD 
FROM TB_EMP A
WHERE A.DEPT_CD = (SELECT A.DEPT_CD  FROM TB_EMP A WHERE A.EMP_NO = '1000000005'); 

-- TB_EMP, TB_SAL_HIS
-- 2020년 5월 기준 평균 이상의 급여를 받고 있는 직원들의 리스트를 출력하시오.

SELECT B.EMP_NO ,B.EMP_NM , A.PAY_DE ,A.PAY_AMT 
FROM TB_SAL_HIS A JOIN TB_EMP B ON A.EMP_NO =B.EMP_NO 
WHERE A.PAY_DE ='20200525' AND A.PAY_AMT 
>= (SELECT AVG(D.PAY_AMT) FROM TB_SAL_HIS D WHERE D.PAY_DE = '20200525'); 

--  서브쿼리
SELECT AVG(A.PAY_AMT)
FROM TB_SAL_HIS A 
WHERE A.PAY_DE LIKE '20200525';

