-- TB_CERTI
DROP TABLE EZEN.TB_CERTI purge;
CREATE TABLE EZEN.TB_CERTI
(
	CERTI_CD char(6) NOT NULL 
	,CERTI_NM varchar2(150) NOT NULL
	,ISSUE_INSTI_NM	varchar2(150) NOT null
);

ALTER TABLE EZEN.TB_CERTI ADD CONSTRAINT PK_TB_CERTI PRIMARY KEY(CERTI_CD);

COMMENT ON COLUMN EZEN.TB_CERTI.CERTI_CD IS '자격증코드';
COMMENT ON COLUMN EZEN.TB_CERTI.CERTI_NM IS '자격증명';
COMMENT ON COLUMN EZEN.TB_CERTI.ISSUE_INSTI_NM IS '발행기관명';
COMMENT ON TABLE EZEN.TB_CERTI IS '자격증';

-- TB_DEPT
DROP TABLE EZEN.TB_DEPT purge;
CREATE TABLE EZEN.TB_DEPT
(
	DEPT_CD CHAR(6)	NOT NULL
	,DEPT_NM VARCHAR2(150) NOT NULL
	,UPPER_DEPT_CD CHAR(6)
);

ALTER TABLE EZEN.TB_DEPT ADD CONSTRAINT PK_TB_DEPT PRIMARY KEY(DEPT_CD);

COMMENT ON COLUMN EZEN.TB_DEPT.DEPT_CD IS '부서코드';
COMMENT ON COLUMN EZEN.TB_DEPT.DEPT_NM IS '부서명';
COMMENT ON COLUMN EZEN.TB_DEPT.UPPER_DEPT_CD IS '상위부서코드';
COMMENT ON COLUMN EZEN.TB_DEPT IS '부서';

-- TB_EMP
DROP TABLE EZEN.TB_EMP purge;
CREATE TABLE EZEN.TB_EMP
(
	EMP_NO char(10)	NOT NULL
	,EMP_NAME varchar2(150)	NOT NULL
	,BIRTH_DE char(8) NOT NULL 
	,LUNAR_YN char(1) NOT NULL
	,SEX_CD char(3) NOT NULL
	,ADDR varchar2(1000) NOT NULL
	,TEL_NO varchar2(150) NOT NULL
	,FINAL_EDU_SE_CD char(3) NOT NULL 
	,SAL_TRANS_BANK_CD  char(3) NOT NULL
	,SAL_TRANS_ACCNT_NO varchar2(20) NOT NULL
	,DIRECT_MANAGER_EMP_NO char(10)
	,DEPT_CD char(6) NOT NULL 
);

ALTER TABLE EZEN.TB_EMP ADD CONSTRAINT PK_TB_EMP PRIMARY key(EMP_NO);
ALTER TABLE EZEN.TB_EMP ADD CONSTRAINT FK_TB_EMP 
FOREIGN KEY (DEPT_CD) REFERENCES ezen.TB_DEPT(DEPT_CD);

COMMENT ON COLUMN EZEN.TB_EMP.EMP_NO IS '사원번호';
COMMENT ON COLUMN EZEN.TB_EMP.emp_name IS '사원명';
COMMENT ON COLUMN EZEN.TB_EMP.birth_de IS '생년월일';
COMMENT ON COLUMN EZEN.TB_EMP.lunar_yn IS '음력여부';
COMMENT ON COLUMN EZEN.TB_EMP.sex_cd IS '성별코드';
COMMENT ON COLUMN EZEN.TB_EMP.addr IS '주소';
COMMENT ON COLUMN EZEN.TB_EMP.tel_no IS '사원번호';
COMMENT ON COLUMN EZEN.TB_EMP.final_edu_se_cd IS '최종학력구분코드';
COMMENT ON COLUMN EZEN.TB_EMP.sal_trans_bank_cd IS '사원번호';
COMMENT ON COLUMN EZEN.TB_EMP.sal_trans_accnt_no IS '급여이체은행코드';
COMMENT ON COLUMN EZEN.TB_EMP.direct_manager_emp_no IS '직속상사사원번호';
COMMENT ON COLUMN EZEN.TB_EMP.dept_cd IS '부서코드';
COMMENT ON TABLE EZEN.TB_EMP IS '사원';


-- TB_EMP_CERTI
DROP TABLE EZEN.TB_EMP_CERTI PURGE;
CREATE TABLE EZEN.TB_EMP_CERTI
(
    EMP_NO CHAR(10) NOT NULL
    ,CERTI_SN CHAR(3) NOT NULL
    ,ACQU_DE CHAR(8) NOT NULL
    ,CERTI_CD CHAR(6) NOT NULL
);

ALTER TABLE EZEN.TB_EMP_CERTI ADD CONSTRAINT PK_TB_EMP_CERTI PRIMARY KEY(EMP_NO,CERTI_SN);
ALTER TABLE EZEN.TB_EMP_CERTI ADD CONSTRAINT FK_TB_EMP_CERTI01 FOREIGN KEY(EMP_NO)REFERENCES EZEN.tb_emp(EMP_NO);
ALTER TABLE EZEN.TB_EMP_CERTI ADD CONSTRAINT FK_TB_EMP_CERTI02 FOREIGN KEY(CERTI_CD)REFERENCES EZEN.tb_certi(CERTI_CD);

COMMENT ON COLUMN EZEN.TB_EMP_CERTI.EMP_NO IS '사원번호';
COMMENT ON COLUMN EZEN.TB_EMP_CERTI.CERTI_SN IS '자격증순번';
COMMENT ON COLUMN EZEN.TB_EMP_CERTI.ACQU_DE IS '취득일자';
COMMENT ON COLUMN EZEN.TB_EMP_CERTI.CERTI_CD IS ' 자격증코드';
COMMENT ON TABLE EZEN.TB_EMP_CERTI IS '사원자격증';

---- TB_SAL
drop table ezen.TB_SAL PURGE;
create table ezen.TB_SAL
(
    SAL_CD     char(6)  not null 
    ,SAL_NM    varchar2(150) not null
);

alter table ezen.tb_sal add constraint PK_TB_SAL PRIMARY KEY(SAL_CD);
comment on COLUMN ezen.TB_SAL.SAL_CD is '급여코드';
comment on COLUMN ezen.TB_SAL.SAL_NM is '급여명';
comment on table ezen.TB_SAL is '급여';

insert into ezen.tb_sal t (t.sal_cd, t.sal_nm) VALUES ('100001', '기본급');
insert into ezen.tb_sal t (t.sal_cd, t.sal_nm) VALUES ('100002', '상여급');
insert into ezen.tb_sal t (t.sal_cd, t.sal_nm) VALUES ('100003', '특별상여급');
insert into ezen.tb_sal t (t.sal_cd, t.sal_nm) VALUES ('100004', '야근수당');
insert into ezen.tb_sal t (t.sal_cd, t.sal_nm) VALUES ('100005', '주말수당');
insert into ezen.tb_sal t (t.sal_cd, t.sal_nm) VALUES ('100006', '점심식대');
insert into ezen.tb_sal t (t.sal_cd, t.sal_nm) VALUES ('100007', '복지포인트');
commit;

-- TB_SAL_HIS
DROP TABLE EZEN.TB_SAL_HIS PURGE;
CREATE TABLE EZEN.TB_SAL_HIS
(
    SAL_HIS_NO CHAR(14) NOT NULL
    ,PAY_DE CHAR(8) NOT NULL
    ,PAY_AMT NUMBER(15) NOT NULL
    ,EMP_NO CHAR(10) NOT NULL
);

ALTER TABLE EZEN.TB_SAL_HIS ADD CONSTRAINT PK_TB_SAL_HIS PRIMARY KEY(SAL_HIS_NO);
ALTER TABLE EZEN.TB_SAL_HIS ADD CONSTRAINT FK_TB_SAL_HIS01 FOREIGN KEY(EMP_NO) REFERENCES EZEN.tb_emp(EMP_NO);

COMMENT ON COLUMN EZEN.TB_SAL_HIS.SAL_HIS_NO IS '급여내역번호';
COMMENT ON COLUMN EZEN.TB_SAL_HIS.PAY_DE IS '지급일자';
COMMENT ON COLUMN EZEN.TB_SAL_HIS.PAY_AMT IS '지급금액';
COMMENT ON COLUMN EZEN.TB_SAL_HIS.EMP_NO IS '사원번호';
COMMENT ON TABLE EZEN.TB_SAL_HIS IS '급여내역';


-- TB_SAL_HIS_DTL
DROP TABLE EZEN.TB_SAL_HIS_DTL PURGE;
CREATE TABLE EZEN.TB_SAL_HIS_DTL
(
    SAL_HIS_NO CHAR(14) NOT NULL
    ,DTL_SN CHAR(3) NOT NULL
    ,SAL_CD CHAR(6) NOT NULL
    ,PAY_DTL_AMT NUMBER(15) NOT NULL
);
















