-- 자격증 
DROP TABLE EZEN.TB_CERTI purge;
CREATE TABLE EZEN.TB_CERTI purge(
		certi_cd char(6) NOT NULL,
		certi_nm varchar2(150) NOT NULL,
		issue_insti.nm varchar2(150) NOT null
);

ALTER TABLE Ezen.tb_certi ADD CONSTRAINT pk_tb_certi PRIMARY key(certi_cd);

comment ON COLUMN ezen.tb_certi.certi_cd IS '자격증코드';
COMMENT ON COLUMN ezen.tb_certi.certi_nm IS '자격증명';
COMMENT ON COLUMN ezen.TB_CERTI.ISSUE_INSTI_NM IS '발행기관명';
COMMENT ON TABLE EZEN.TB_CERTI IS '자격증';

-- 부서

DROP TABLE EZEN.TB_DEPT purge;
CREATE TABLE EZEN.TB_DEPT(
		DEPT_CD CHAR(6) NOT NULL,
		DEPT_NM VARCHAR2(150) NOT NULL,
		DEPT_UPPER_DEPT_CD CHAR(6)
);

ALTER TABLE EZEN.TB.DEPT ADD CONSTRAINT PK_TB_DEPT PRIMARY KEY(DEPT_CD);

COMMENT ON COLUMN EZEN.TB_DEPT.DEPT_CD IS '부서코드';
COMMENT ON COLUMN EZEN.TB_DEPT.DEPT_NM IS '부서명';
COMMENT ON COLUMN EZEN.TB_DEPT_UPPER_DEPT_CD IS '상위부서코드';
COMMENT ON COLUMN EZEN.TB_DEPT IS '부서';